### ISSUE TITLE
Overflowing integers

### ISSUE THREAD

**Issue by peterdesmet** [inbo/datapackage#16]
```r
> pkg <- read_package("https://zenodo.org/record/5056105/files/datapackage.json")
> gps <- read_resource(pkg, "gps")
Warning: 2690 parsing failures.
row      col   expected      actual                                                                file
  1 event-id an integer 19193113855 'https://zenodo.org/record/5056105/files/MH_ANTWERPEN-gps-2018.csv'
  2 event-id an integer 19193113856 'https://zenodo.org/record/5056105/files/MH_ANTWERPEN-gps-2018.csv'
  3 event-id an integer 19193113857 'https://zenodo.org/record/5056105/files/MH_ANTWERPEN-gps-2018.csv'
  4 event-id an integer 19193113858 'https://zenodo.org/record/5056105/files/MH_ANTWERPEN-gps-2018.csv'
  5 event-id an integer 19193113859 'https://zenodo.org/record/5056105/files/MH_ANTWERPEN-gps-2018.csv'
```

Integers (https://specs.frictionlessdata.io/table-schema/#integer) can be valid in Frictionless, but too big for R. The data frame will still be loaded, but the column will contain `NA` for overflowing integers. The whole column would better be cast to `numeric`.

@damianooldoni Is there a way we can achieve that, but _only_ if there are overflow values?

**Comment by damianooldoni** [comment]
Yes, this is something annoying. The only solution I can figure out is to read everything as double (`col_double()`) and then setting back to integers where possible. Here below a small reproducible example based on this a test file called [test_integer.txt](https://github.com/inbo/datapackage/files/6753172/test_integer.txt). I used the most updated way to work with conditional transformation in `dplyr`, i.e. using `across()`

```r
library(readr)
library(dplyr)
# read file
a <- read_csv("./test_integer.txt")
#> 
#> -- Column specification --------------------------------------------------------
#> cols(
#>   col1 = col_double(),
#>   col2 = col_double(),
#>   col3 = col_double(),
#>   col4 = col_character()
#> )
a
#> # A tibble: 3 x 4
#>    col1    col2  col3 col4   
#>   <dbl>   <dbl> <dbl> <chr>  
#> 1   1.3 1.31e15   123 Peter  
#> 2  13.2 1.1 e 1    44 Peter  
#> 3  23   1   e 0     2 Damiano

# define which columns are integers
int_cols <- c("col2", "col3")

# transform them to integers if possible
a <- a %>% mutate(across(all_of(int_cols),
                         ~ ifelse(max(.x, na.rm = TRUE) < .Machine$integer.max,
                                  as.integer(.x),
                                  .x)))
# show result
a
#> # A tibble: 3 x 4
#>    col1    col2  col3 col4   
#>   <dbl>   <dbl> <int> <chr>  
#> 1   1.3 1.31e15   123 Peter  
#> 2  13.2 1.31e15   123 Peter  
#> 3  23   1.31e15   123 Damiano
```
Created on 2021-07-02 by the reprex package (v2.0.0)

**Comment by peterdesmet** [comment]
Thanks, the result I'm getting is still a double:

```
# A tibble: 3 x 4
   col1    col2  col3 col4   
  <dbl>   <dbl> <dbl> <chr>  
1   1.3 1.31e15   123 Peter  
2  13.2 1.1 e 1    44 Peter  
3  23   1   e 0     2 Damiano
```

But the integer problem seems like something bigger than this package should solve. Users can always update a column type by overwriting it in the metadata. 🤷‍♂️

**Comment by damianooldoni** [comment]
1. Strange you get it not fixed as `reprex` makes things reproducible as the name itself means :smile: 
2. I agree that you can leave as it is and set all as double.

**Comment by peterdesmet** [comment]
> 2. I agree that you can leave as it is and set all as double.

You mean: have the user set this, rather than setting _all_ integers as doubles?

**Comment by peterdesmet** [comment]
Ha, I notice that when I cast as double and then write the tibble to csv, it doesn't at false precision. In other words `19193113855` in an input csv is still written as `19193113855` in `write_csv()`. So maybe there is no downside to using numbers?

**Comment by damianooldoni** [comment]
Well, double is not synonym of real numbers. So, integers of class `double` will be written on file correctly.

**Comment by peterdesmet** [comment]
Update in 1719fc2: all integers will now be read as doubles. Less annoying for users.

**Comment by peterdesmet** [comment]
Update, integers are cast to `numeric`, just like numbers are: c924b96 @damianooldoni tested that this doesn't add false precision when writing to csv.
