### ISSUE TITLE
Support integer `bareNumber=FALSE`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/datapackage#17]
The frictionless specs allow integers to have non-numeric character, e.g. `€35` or `35$`, if they set `bareNumber=FALSE` (default `TRUE`): https://specs.frictionlessdata.io/table-schema/#integer

Have to look into if and how to implement this.

**Comment by damianooldoni** [comment]
I think we can use [`units`](https://r-quantities.github.io/units/articles/measurement_units_in_R.html) package for this.

**Comment by damianooldoni** [comment]
Valid units can be found by this commando:

```r
valid_udunits()
```

Euro or dollars are not, but you can add any kind of unit via `install_unit()`

**Comment by peterdesmet** [comment]
The implementation only has to strip the non-numerical characters, so the number remains. Is that something units does?

**Comment by damianooldoni** [comment]
if you want to strip the non-numerical characters, then you have only to use `col_number()` while specifying the column data type. See `??col_number` for more info about it.

**Comment by peterdesmet** [comment]
Ha, indeed, this is done by default for `col_number()`, but not for `col_double()` (which we use for integers):

```R
Warning: 3 parsing failures.
row           col               expected actual                           file
  1 deployment_id no trailing characters   10%  'inst/extdata/deployments.csv'
  2 deployment_id a double                 €23  'inst/extdata/deployments.csv'
  3 deployment_id no trailing characters   3.3$ 'inst/extdata/deployments.csv'
```

**Comment by peterdesmet** [comment]
This is now implemented and covered with a test https://github.com/inbo/datapackage/pull/24/commits/96c2740d814635acfe4bbe65afb52e3a4a2bfa6e#diff-2eaa9bcae72e0b467f3122192f8244e730cd8d3a8cbe803529902553f9601ac3
