### ISSUE TITLE
Message users to make sure they can use data

### ISSUE THREAD

**Issue by peterdesmet** [inbo/datapackage#21]
When using `read_package()` a generic **short** message could be printed to console to warn users to follow data licenses and guidelines and read metadata. This would be on by default, but maybe we can add an option to silence it.

**Comment by peterdesmet** [comment]
GBIF has:

> While data from GBIF.org is free and open, please remember that by downloading this data, you are agreeing:
>
> — to abide by the GBIF user agreement
> — and, if you use the data, to cite it appropriately
> 
> Please make sure your citation includes the unique DOI (shown on the page once it refreshes). The use of properly formatted data citations ensures scientific transparency and reproducibility and enables proper attribution of credit to the data providers.
> 
> If you are analysing the data you will download, please consider referencing this citation in your Materials and methods section.

**Comment by peterdesmet** [comment]
> Please make sure you have the right to use data from this Data Package. For more information, see `$id`

The second sentence would be added if `$id` is a URL (e.g. a DOI).

**Comment by peterdesmet** [comment]
Ping @sarahcd

**Comment by sarahcd** [comment]
Good addition! Here is a slight edit to cover a variety of use cases:

Please make sure you have the right to access data from this Data Package for your proposed use, and follow applicable requests or requirements to credit the dataset and its authors. For more information, see $id

As other examples, here's the relevant guidance from Movebank:
https://www.movebank.org/cms/movebank-content/general-movebank-terms-of-use
https://www.movebank.org/cms/movebank-content/citation-guidelines

**Comment by peterdesmet** [comment]
Thanks, I've split it into two sentences for readability. The "For more info" appears on a second line and is conditional:

<img width="615" alt="Screenshot 2021-07-06 at 17 58 34" src="https://user-images.githubusercontent.com/600993/124631560-ce68f880-de83-11eb-927d-40e3be8657fb.png">

I've also reworded `requests` to `norms`, which is broader.
